CREATE proc h.populate_data as
begin


truncate table [FlightAction]
--go
INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (4, N'Set New Location ', 1, N'Pending', 2, 1, 0, 0, 0, 3, NULL, N'WayPointNum', 1, 0, 1, N'InFlight', 3, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (5, N'Set New Location ', 1, N'InFlight', 3, 1, NULL, 0, 0, 3, NULL, N'WayPointNum', 1, 0, 0, NULL, NULL, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (6, N'Set New Location ', 1, N'InFlight', 3, 0, NULL, 0, 0, 3, N'-10', N'WayPointNum', 1, 0, 0, NULL, NULL, 0, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (7, N'Set New Location ', 1, NULL, NULL, NULL, NULL, 1, 0, 3, N'-9', N'WayPointNum', 1, 0, 1, N'Terminated', 5, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (8, N'Get Flight ID', 2, NULL, NULL, NULL, NULL, NULL, 0, 3, NULL, N'FlightID', 0, 1, 1, N'Pending', 2, 0, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (9, N'Get Last WayPointID', 3, N'InFlight', 3, NULL, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0, N'False', NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (10, N'Stop/Close Flight', 4, N'InFlight', 3, NULL, NULL, 0, 0, 0, NULL, N'Ended - Stop/Close Flight', 0, 0, 1, N'Ended', 4, NULL, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (12, N'Set New Location ', 1, N'NotStarted', 1, 0, 1, 0, 0, 1, NULL, N'-7', 0, 0, 1, N'Pending', 2, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (13, N'Set New Location ', 1, N'Pending', 2, 0, 1, 0, 0, 1, NULL, N'-7', 0, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (14, N'Set New Location ', 1, N'Pending', 2, 1, 1, 0, 0, 3, NULL, N'WayPointNum', 1, 0, 1, N'InFlight', 3, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (15, N'Set New Location ', 1, N'InFlight', 3, 1, 1, 0, 0, 3, NULL, N'WayPointNum', 1, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (18, N'Get Last WayPointID', 3, N'InFlight', 3, NULL, 1, 0, 0, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (21, N'Get Last WayPointID', 3, N'Pending', 2, NULL, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (22, N'Get Last WayPointID', 3, N'Pending', 2, NULL, 0, 0, 0, 0, NULL, N'-1', 0, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (23, N'Get Last WayPointID', 3, N'NotStarted', 1, NULL, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (24, N'Get Last WayPointID', 3, N'NotStarted', 1, NULL, 1, 0, 0, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (25, N'Stop/Close Flight', 4, N'Terminated', 5, NULL, NULL, NULL, NULL, 0, NULL, N'Flight Terminated', 0, 0, 1, N'Terminated', 5, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (26, N'Stop/Close Flight', 4, N'Terminated', 5, NULL, NULL, NULL, NULL, 0, NULL, N'0', 0, 0, NULL, N'Terminated', 5, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (27, N'Stop/Close Flight on Limit', 5, N'InFlight', 3, NULL, 0, 0, 0, 0, NULL, N'0', 0, 0, 1, N'Ended on Limit', 5, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (28, N'Stop/Close Flight on Limit', 5, N'InFlight', 3, NULL, 1, 0, 0, 0, NULL, N'0', 0, 0, 1, N'Ended on Limit', 5, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (29, N'Stop/Close Flight', 4, N'Pending', 2, NULL, 0, 0, 0, 3, NULL, N'0', 0, 0, 1, N'Ended', 4, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (30, N'Stop/Close Flight', 4, N'Pending', 2, NULL, 1, 0, 0, 0, NULL, N'Ended in Pending', 0, 0, 1, N'Ended', 4, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (31, N'Set New Location ', 1, N'Stopped', 4, 1, NULL, 0, 0, 3, NULL, N'WayPointID', 1, 0, 1, N'Stopped', 4, 1, NULL)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (32, N'Set New Location ', 1, N'Terminated', 5, NULL, NULL, NULL, NULL, 3, NULL, N'WayPointID', 1, 0, 1, N'InFlight', 3, 1, 1)

INSERT [dbo].[FlightAction] ([FlightActionID], [Request], [RequestID], [FlightState], [FlightStateID], [IsAboveSpeedBottomTreshhold], [IsPattern], [IsMaxAllowedPointsReached], [IsRoad], [r_ResponseType], [r_ResponseCommand], [r_ResponseData], [a_IsSetLocation], [a_IsCreateFlight], [a_IsUpdFlightStatus], [a_IsUpdFlightStatus_FlightState], [a_IsUpdFlightStatus_FlightStateID], [a_IsUpdFlightAttrib], [isActive]) VALUES (33, N'Set New Location ', 1, N'InFlight', 3, 1, NULL, NULL, 1, 3, N'-6', N'WayPointID', 1, 0, 1, N'Terminated', 5, 1, 1)
end