CREATE TABLE [dbo].[CommunicationLog] (
    [CommunicationlogID] INT            IDENTITY (1, 1) NOT NULL,
    [rcode]              NVARCHAR (250) NULL,
    [flightid]           NVARCHAR (250) NULL,
    [speed]              NVARCHAR (250) NULL,
    [speedlowflag]       NVARCHAR (250) NULL,
    [phonenumber]        NVARCHAR (250) NULL,
    [deviceid]           NVARCHAR (250) NULL,
    [aid]                NVARCHAR (250) NULL,
    [AcftMake]           NVARCHAR (250) NULL,
    [AcftModel]          NVARCHAR (250) NULL,
    [AcftSeries]         NVARCHAR (250) NULL,
    [AcftRegNum]         NVARCHAR (250) NULL,
    [AcftTagId]          NVARCHAR (250) NULL,
    [isFlyingPattern]    NVARCHAR (250) NULL,
    [speed_thresh]       NVARCHAR (250) NULL,
    [latitude]           NVARCHAR (250) NULL,
    [longitude]          NVARCHAR (250) NULL,
    [accuracy]           NVARCHAR (250) NULL,
    [extrainfo]          NVARCHAR (250) NULL,
    [wpntnum]            NVARCHAR (250) NULL,
    [return_response]    NVARCHAR (250) NULL,
    [Created]            DATETIME       CONSTRAINT [DF_CommunicationLog_Created] DEFAULT (getdate()) NULL,
    [Updated]            DATETIME       NULL,
    [AcftName]           NVARCHAR (100) NULL,
    [userid]             NVARCHAR (50)  NULL,
    [username]           NVARCHAR (20)  NULL,
    [freq]               NVARCHAR (20)  NULL,
    [routeId]            NVARCHAR (20)  NULL,
    [appversioncode]     NVARCHAR (20)  NULL,
    [elevcheck]          NVARCHAR (20)  NULL,
    CONSTRAINT [PK_CommunicationLog] PRIMARY KEY CLUSTERED ([CommunicationlogID] ASC)
);

