CREATE TABLE [dbo].[FlightController] (
    [FlightControllerID]                    INT          IDENTITY (1, 1) NOT NULL,
    [ChecksumID_Request]                    AS           (checksum([RequestID],[FlightStateID],[IsPattern],[IsAboveSpeedBottomTreshhold],[IsRoad],[IsMaxAllowedPointsReached])),
    [r_ChecksumID_Response]                 INT          NULL,
    [ChecksumID_FlightIncl]                 AS           (checksum([RequestID],[FlightID],[FlightStateID],[IsPattern],[IsAboveSpeedBottomTreshhold],[IsRoad],[IsMaxAllowedPointsReached])),
    [RequestID]                             INT          NULL,
    [FlightStateID]                         INT          NULL,
    [FlightID]                              INT          NULL,
    [FlightID_UpdateNumber]                 INT          NULL,
    [IsAboveSpeedBottomTreshhold]           BIT          NULL,
    [IsPattern]                             BIT          NULL,
    [IsMaxAllowedPointsReached]             BIT          NULL,
    [IsRoad]                                BIT          NULL,
    [r_ResponseType]                        INT          NULL,
    [r_ResponseCommand]                     VARCHAR (50) NULL,
    [r_ResponseData]                        VARCHAR (50) NULL,
    [a_IsSetLocation]                       BIT          NULL,
    [a_IsCreateFlight]                      BIT          NULL,
    [a_IsUpdFlightStatus]                   BIT          NULL,
    [a_IsUpdFlightStatus_FlightState]       VARCHAR (50) NULL,
    [a_IsUpdFlightStatus_FlightStateID]     INT          NULL,
    [a_IsUpdFlightAttrib]                   BIT          NULL,
    [a_IsUpdFlightAttrib_LastGPSLocationID] INT          NULL,
    [a_IsUpdFlightAttrib_Points]            INT          NULL,
    [a_FlightActionID]                      INT          NULL,
    [Created]                               DATETIME     CONSTRAINT [DF_FlightController_Created] DEFAULT (getdate()) NULL,
    [Updated]                               DATETIME     NULL,
    CONSTRAINT [PK_FlightController] PRIMARY KEY CLUSTERED ([FlightControllerID] ASC),
    CONSTRAINT [FK_FlightController_Flight] FOREIGN KEY ([FlightID]) REFERENCES [dbo].[Flight] ([FlightID]) ON DELETE CASCADE
);

