CREATE TABLE [dbo].[Flight] (
    [FlightID]                  INT            IDENTITY (1, 1) NOT NULL,
    [FlightCode]                VARCHAR (250)  NULL,
    [FlightName]                VARCHAR (250)  NULL,
    [FlightDate]                DATETIME       CONSTRAINT [DF_Flight_FlightDate] DEFAULT (getdate()) NULL,
    [CreatedUTC]                DATETIME2 (7)  CONSTRAINT [DF_Flight_FlightDateChar] DEFAULT (getutcdate()) NOT NULL,
    [FlightTimeStart]           DATETIME       NULL,
    [FlightDurationMin]         INT            NULL,
    [AcftID]                    INT            NULL,
    [PilotID]                   INT            NULL,
    [AcftPilotID]               INT            NULL,
    [IsPattern]                 BIT            NULL,
    [IsShared]                  BIT            NULL,
    [Last_GPSLocationID]        INT            NULL,
    [Comments]                  NVARCHAR (250) NULL,
    [Created]                   DATETIME       CONSTRAINT [DF_Flight_Created] DEFAULT (getdate()) NULL,
    [Updated]                   DATETIME       CONSTRAINT [DF_Flight_Updated] DEFAULT (getdate()) NULL,
    [Active]                    INT            CONSTRAINT [DF_Flight_Active] DEFAULT ((1)) NULL,
    [Points]                    INT            NULL,
    [FlightStateID]             INT            NULL,
    [FlightControllerID]        INT            NULL,
    [InProcess]                 BIT            NULL,
    [SpeedThreshhold]           INT            NULL,
    [FreqSec]                   INT            NULL,
    [RouteID]                   INT            NULL,
    [AppVersionCode]            INT            NULL,
    [IsNameUpdated]             BIT            NULL,
    [AreaID]                    INT            NULL,
    [IsJunk]                    BIT            CONSTRAINT [DF_Flight_IsJunk] DEFAULT ((1)) NULL,
    [IsAltitudeChecked]         BIT            NULL,
    [FlightStart_GPSLocationID] INT            NULL,
    [IsChecked]                 BIT            NULL,
    CONSTRAINT [PK_Flight] PRIMARY KEY CLUSTERED ([FlightID] ASC)
);

